spring.application.name=jobtracker

spring.datasource.url=jdbc:postgresql://localhost:5432/jobtracker
spring.datasource.username=jobtracker
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.web.error.include-stacktrace=never

jwt.secret=ThisIsMyDevelopmentSecretKeyForJwtSigningItNeedsToBeAtLeast256BitsLongForHS256
jwt.expiration=86400000
